Easy.Admin/Controllers/ManagerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gxu.Models;

namespace Easy.Admin.Controllers
{
    [DisplayName("系统管理")]
    public class ManagerController : Controller
    {
        // GET: Manager
        public ViewResult Index()
        {
            return View();
        }

        // GET: Manager
        public ViewResult Test()
        {
            return View();
        }

        // GET: /Menu/
        /// <summary>
        /// 获取菜单
        /// </summary>
        /// <returns></returns>
        public ActionResult GetMenu()
        {
            var list = Menus.FindAll(Menus._.Remove == false, "", "", 0, 0).ToList();

            return Json(Menus.ToTreeEntities(list));

        }
        //
        // GET: /Menu/
        ///// <summary>
        ///// 获取菜单
        ///// </summary>
        ///// <returns></returns>
        //public ActionResult GetAllMenu()
        //{
        //   var list = Menus.FindAll("Remove", false);

        //    //list = Menu.FindAll("Remove = 0", "Depth,Sort,ID", "", 0, 0);
        //    List<TreeEntity> models = new List<TreeEntity>();
        //    var lst = list.OrderBy(f => f.ParentID).OrderBy(f => f.Sort).ToList();
        //    foreach (var n in lst)
        //    {
        //        if (n.Remove)
        //            continue;
        //        var tree = new TreeEntity()
        //        {
        //            complete = true,
        //            id = n.ID.ToString(),
        //            //hasChildren = n.HasChilds,
        //            hasChildren = n.IsChild,
        //            //name = n.ResourceName,
        //            name = n.Name,
        //            //value = n.ResourceUrl,
        //            value = n.ID.ToString(),
        //            //url = "../" + n.ResourceUrl,
        //            target = "frmright",
        //            showProgess = false,
        //            parentId = n.ParentID.ToString(),
        //            ActionIDs = n.ActionIDs
        //            //parentId = n.Pid.ToString()
        //        };
        //        models.Add(tree);
        //    }

        //    Hashtable has = new Hashtable();
        //    has.Add("treeNodes", models);
        //    return Json(has);
        //}
        //[HttpPost]
        //public ActionResult getActionDataList()
        //{
        //    var list = Actions.FindAll("IsGroup=0", "ParentID,ID", "", 0, 0);
        //    Hashtable result = new Hashtable();
        //    result.Add("pager.pageNo", 1);
        //    result.Add("rows", list);
        //    result.Add("pager.totalRows", list.Count);
        //    return Json(result);
        //}
        //[HttpPost]
        //[ActionDesc("保存菜单操作关联", "允许保存菜单操作关联", groupName: "系统管理")]
        //[AJAXResult]
        //public ActionResult SaveMenu(Menus m)
        //{
        //    if (m.ID > 0 && !string.IsNullOrWhiteSpace(m.ActionIDs))
        //    {
        //        var ids = m.ActionIDs.Split(",");
        //        MenuActionMap.Delete(new string[] { "MenuID" }, new object[] { m.ID });
        //        foreach (var item in ids)
        //        {
        //            int id = 0;
        //            if (int.TryParse(item, out id))
        //            {
        //                MenuActionMap ma = new MenuActionMap();
        //                ma.ActionID = id;
        //                ma.MenuID = m.ID;
        //                ma.Insert();
        //            }
        //        }
        //    }
        //    return Json(new AjaxResult("保存成功", true));
        //}
        ///// <summary>
        ///// 注册菜单
        ///// </summary>
        ///// <returns></returns>
        //[ActionDesc("注册菜单", "设置系统菜单信息")]
        //public ActionResult RegisterMenu()
        //{
        //    //获取所有程序集中类型名包含 Controller 的类型
        //    var allTypes = AppDomain.CurrentDomain.GetAssemblies().SelectMany(sm => sm.GetTypes().Where(w => w.Name.EndsWith("Controller"))).ToArray();

        //    //通过ActionDescAttribute MenuDescAttribute 特性过滤并构造菜单实体
        //    var menuEntities = MenuDescManage.GetAllMenus(allTypes);

        //    //根据GroupName 分组
        //    var groupMenuEntities = menuEntities.GroupBy(f => f.GroupName);

        //    //存放所有菜单
        //    var menus = new List<Menus>(menuEntities.Count);

        //    //一个ActionEntity对应的多个菜单 形式的字典
        //    var dic = new Dictionary<ActionEntity, List<Menus>>();

        //    //处理菜单分组
        //    foreach (var item in groupMenuEntities)
        //    {
        //        //取第一条菜单实体
        //        var pm = menuEntities.FirstOrDefault(w => w.Name.EqualIgnoreCase(item.Key));

        //        Func<MenuEntity, bool> c = (o) => true;

        //        // - 分割分组名，按顺序构成多级菜单
        //        var menukey = item.Key.Split('-');

        //        int num = menukey.Count();

        //        //父级菜单，此变量每复制一次，就将以上 - 分割的分组名组合成多级菜单关联
        //        var parentMenu = new Menus();

        //        //记录一个ActionEntity对应的所有菜单
        //        var amenu = new List<Menus>();

        //        if (pm?.ActionEntity != null)
        //        {
        //            if (dic.ContainsKey(pm.ActionEntity))
        //            {
        //                amenu = dic[pm.ActionEntity];
        //            }
        //        }

        //        //根据 - 分割key的数组，循环产生顶级菜单，前一个作为后一个的父级，产生三级菜单，多级菜单设置多个 - 连接即可
        //        for (int i = 0; i < num; i++)
        //        {
        //            var cur = new Menus
        //            {
        //                Name = menukey[i],//item.Key,
        //                //State = State.Normal,
        //                ChildNum = 1,
        //                Sort = pm?.Order ?? 0,
        //                Parent = parentMenu,//这个parentMenu可能是前一个cur，因为class是引用类型，所以可以构成多级引用的菜单
        //            };
        //            if (!amenu.Contains(cur))
        //                amenu.Add(cur);
        //            menus.Add(cur);
        //            parentMenu = cur;
        //        }

        //        //循环处理该key下的所有菜单
        //        foreach (var subItem in item)
        //        {
        //            parentMenu.Render = subItem.Render;
        //            parentMenu.IsSys = subItem.IsSys;
        //            var subMenu = new Menus
        //            {
        //                Name = subItem.Name,
        //                Description = subItem.Desc,
        //                URL = subItem.Url,
        //                Controller = subItem.Controller,
        //                Action = subItem.Action,
        //                Parameters = subItem.Parameters,
        //                //State = State.Normal,
        //                Parent = parentMenu,
        //                Sort = subItem.Order,
        //                Render = subItem.Render,
        //                IsSys = subItem.IsSys
        //            };

        //            var orders = (subItem?.OrderStr?.Split('-') ?? new[] { subItem.Order + "" }).Select(s => s.ToInt()).Reverse().ToArray();
        //            SetOrder(0, subMenu, orders);



        //            menus.Add(subMenu);

        //            //处理action
        //            if (subItem.ActionEntity != null)
        //            {
        //                if (dic.ContainsKey(subItem.ActionEntity))
        //                {
        //                    var sublist = dic[subItem.ActionEntity];
        //                    if (!sublist.Contains(parentMenu))
        //                        sublist.Add(parentMenu);
        //                    if (!sublist.Contains(subMenu))
        //                        sublist.Add(subMenu);
        //                    dic[subItem.ActionEntity] = sublist;
        //                }
        //                else
        //                {
        //                    dic.Add(subItem.ActionEntity, new List<Menus> { parentMenu, subMenu });
        //                }
        //            }
        //            if (!amenu.Contains(subMenu))
        //                amenu.Add(subMenu);
        //        }
        //        if (pm?.ActionEntity != null)
        //        {
        //            if (!dic.ContainsKey(pm.ActionEntity))
        //            {
        //                dic.Add(pm.ActionEntity, amenu);
        //            }
        //            else
        //            {
        //                dic[pm.ActionEntity] = amenu;
        //            }
        //        }
        //    }
        //    MenuManage.Register(menus, RegisteredBehaviour.Replace);
        //    var actionEntities = ActionManager.GetAllActions(allTypes.ToArray());
        //    foreach (var item in actionEntities)
        //    {
        //        if (!string.IsNullOrWhiteSpace(item.GroupName))
        //        {
        //            var p = Actions.Find(new string[] { "Name", "IsGroup" }, new object[] { item.GroupName, true });
        //            if (p == null)
        //            {
        //                p = new Actions
        //                {
        //                    Name = item.GroupName,
        //                    Description = item.Desc,
        //                    Code = item.Code,
        //                    Remove = false,
        //                    IsSys = item.IsSys,
        //                    IsGroup = true
        //                };
        //                p.Insert();
        //            }
        //            var cur = Actions.Find(new string[] { "Name", "ParentID" }, new object[] { item.Name, p.ID });
        //            if (cur == null)
        //            {
        //                cur = new Actions
        //                {
        //                    Name = item.Name,
        //                    Description = item.Desc,
        //                    Code = item.Code,
        //                    //State = State.Normal,
        //                    Remove = false,

Easy.Admin/Views/Manager/Left.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="nav-close">
        <i class="fa fa-times-circle"></i>
    </div>
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                   @* <span><img width="64" height="64" alt="image" class="img-circle" src="/UploadFiles/GetFile/d226ad89-f390-4e57-932d-a71ae6c402f5" /></span>*@
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs"><strong class="font-bold">姓名：@*@(Gxu.Cisco.BLL.UserLogin.CurrUserData?.RealName ?? "未登录")*@</strong></span>
                            <span class="text-muted text-xs block">角色：@*@(Gxu.Cisco.BLL.UserLogin.CurrUserData?.AdminTypeName ?? "未登录")*@<b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li>
                            <a class="J_menuItem" href="">修改头像</a>
                        </li>
                        <li>
                            <a class="J_menuItem" href="">个人资料</a>
                        </li>
                        <li>
                            <a class="J_menuItem" href="">联系我们</a>
                        </li>
                        <li>
                            <a class="J_menuItem" href="">信箱</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Account")">安全退出</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                    <a href="#">
                        <i class="fa fa-home"></i>
                        <span class="nav-label">主页</span>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a class="J_menuItem" href="index_v1.html" data-index="0">主页示例一</a>
                        </li>
                        <li>
                            <a class="J_menuItem" href="index_v2.html">主页示例二</a>
                        </li>
                        <li>
                            <a class="J_menuItem" href="index_v3.html">主页示例三</a>
                        </li>
                        <li>
                            <a class="J_menuItem" href="index_v4.html">主页示例四</a>
                        </li>
                    </ul>

                </li>
        </ul>
    </div>
</nav>
<script>
    var initMenu = function () {
        $.post("@Url.Action("GetMenu","Manager")", null, function (result) {
            if (!result || typeof result !== "object" || result.length<1) {
                return;
            }
            menuLoadData(result);
            //渲染菜单
            $("#side-menu").metisMenu();
            contabs();
        });

        $("#side-menu").metisMenu();
        contabs();
        function menuLoadData(treeObj) {
            for (var i = 0; i < treeObj.length; i++) {
                var item = treeObj[i];
                dsei(item);
                if (item.hasChildren) {
                    dsei2(item.ChildNodes);
                }
            }
        }
        //一级菜单
        function dsei(data) {
            var ulMenu = $('ul#side-menu');
            var url = data.url ? data.url : "#";
            var fallow = data.hasChildren ? '<span class="fa arrow"></span>' : '';
            var zsul = '<li id="' + data.id + '"><a href="' + url + '"><i class="fa fa-edit "></i> <span class="nav-label">' + fallow+ data.name + '</span></a></li>';
            ulMenu.append(zsul);
        }
        //下级菜单
        function dsei2(data) {
            if (data.length < 1) return;
            var $li = $("li#" + data[0].parentId);//父级li
            var ul = '<ul class="nav nav-second-level"></ul>';//添加子级容器
            $li.append(ul);
            var $ul = $li.find("ul");
            for (var i = 0; i < data.length; i++) {
                var item = data[i];
                var hasChildren = data.hasChildren;
                var url = item.url ? item.url : "#";
                var fallow = hasChildren ? '<span class="fa arrow"></span>' : '';
                var menuTab = hasChildren ? '><i class="fa fa-edit "></i':'class="J_menuItem"';
                var zsul = '<li id="' + item.id + '"><a href="' + url + '" ' + menuTab + '>' + fallow + item.name + '</a></li>';
                $ul.append(zsul);
                if (hasChildren) {
                    dsei2(item.ChildNodes);
                }
            }
        }
    }
</script>